var timelineData = [
  {
    id: "0",
    permalink: "https://hwantage.github.io/posts/hugo/",
    title: "HUGO를 이용한 정적 사이트 생성 및 github pages를 이용한 블로그 운영 방법",
    category: "[Front-end]",
    date: "2024-01-12 13:14:52",
  },
  {
    id: "1",
    permalink: "https://hwantage.github.io/posts/nvm/",
    title: "nvm을 이용한 node.js의 버전 관리 방법",
    category: "[Front-end]",
    date: "2024-01-12 13:14:52",
  },
  {
    id: "2",
    permalink: "https://hwantage.github.io/posts/npm-publish/",
    title: "CSS-Deduplication part 3 (postcss 플러그인을 npmjs.org에 배포)",
    category: "[Front-end]",
    date: "2024-01-14 10:32:14",
  },
  {
    id: "3",
    permalink: "https://hwantage.github.io/posts/css-deduplicate-2/",
    title: "CSS-Deduplication part 2 (CSS 중복제거 플러그인 제작)",
    category: "[Front-end]",
    date: "2024-01-15 13:14:52",
  },
  {
    id: "4",
    permalink: "https://hwantage.github.io/posts/css-deduplicate/",
    title: "CSS-Deduplication part1 (postcss 커스텀 스크립트를 이용한 CSS 중복 제거)",
    category: "[Front-end]",
    date: "2024-01-16 11:14:52",
  },
  {
    id: "5",
    permalink: "https://hwantage.github.io/posts/symboliclink/",
    title: "심볼릭 링크로 마크다운 에디터로 업로드한 이미지 HUGO에서 바로 확인",
    category: "[Front-end]",
    date: "2024-01-16 13:14:52",
  },
  {
    id: "6",
    permalink: "https://hwantage.github.io/posts/fake-terminal/",
    title: "Xterm.js 를 이용한 fake terminal 웹 제작",
    category: "[Front-end]",
    date: "2024-01-19 10:29:50",
  },
  {
    id: "7",
    permalink: "https://hwantage.github.io/posts/google-analytics/",
    title: "HUGO 블로그에 구글 애널리틱스 연결하기",
    category: "[Front-end]",
    date: "2024-01-20 13:14:52",
  },
  {
    id: "8",
    permalink: "https://hwantage.github.io/posts/utterances/",
    title: "HUGO 블로그에 댓글 기능 연동",
    category: "[Front-end]",
    date: "2024-01-20 13:14:52",
  },
  {
    id: "9",
    permalink: "https://hwantage.github.io/posts/google-search-console/",
    title: "HUGO로 제작한 블로그를 구글 검색, 네이버 검색, 다음 검색에 노출시키기",
    category: "[Front-end]",
    date: "2024-01-21 11:14:52",
  },
  {
    id: "10",
    permalink: "https://hwantage.github.io/posts/js-destructuring-assignment/",
    title: "Javascript 비구조화 할당",
    category: "[Javascript]",
    date: "2024-01-22 13:14:52",
  },
  {
    id: "11",
    permalink: "https://hwantage.github.io/posts/js-find/",
    title: "Javascript find, findIndex, filter",
    category: "[Javascript]",
    date: "2024-01-22 14:14:52",
  },
  {
    id: "12",
    permalink: "https://hwantage.github.io/posts/js-serialization/",
    title: "Javascript 직렬화(serialization)",
    category: "[Javascript]",
    date: "2024-01-22 14:14:52",
  },
  {
    id: "13",
    permalink: "https://hwantage.github.io/posts/js-template-literal/",
    title: "Javascript 템플릿 리터럴(Template literal)",
    category: "[Javascript]",
    date: "2024-01-22 14:14:52",
  },
  {
    id: "14",
    permalink: "https://hwantage.github.io/posts/js-function/",
    title: "Javascript 함수 선언 방법과 호이스팅",
    category: "[Javascript]",
    date: "2024-01-22 14:14:52",
  },
  {
    id: "15",
    permalink: "https://hwantage.github.io/posts/js-performance-coding/",
    title: "Javascript 성능 향상 코딩 팁",
    category: "[Javascript]",
    date: "2024-01-23 14:14:52",
  },
  {
    id: "16",
    permalink: "https://hwantage.github.io/posts/hugo-deploy-automation/",
    title: "HUGO 사이트 배포를 위한 배치 파일 생성",
    category: "[Front-end]",
    date: "2024-01-27 13:14:52",
  },
];
